import type {
  CashFlowPoint,
  MoneyAccount,
  MoneyTransaction,
} from "./types";

export const MOCK_USER_ID = "user_mock_arjun";

export const SEED_ACCOUNTS: MoneyAccount[] = [
  {
    id: "acct_chase_checking",
    userId: MOCK_USER_ID,
    name: "Chase Checking",
    type: "asset.bank.current",
    institution: "Chase",
    accountNumberMasked: ".... 4821",
    currency: "INR",
    balance: 12430.58,
  },
  {
    id: "acct_marcus_savings",
    userId: MOCK_USER_ID,
    name: "Marcus Savings",
    type: "asset.bank.savings",
    institution: "Marcus",
    accountNumberMasked: ".... 9204",
    currency: "INR",
    balance: 45200,
  },
  {
    id: "acct_fidelity",
    userId: MOCK_USER_ID,
    name: "Fidelity Brokerage",
    type: "asset.investment",
    institution: "Fidelity",
    accountNumberMasked: ".... 7731",
    currency: "INR",
    balance: 284320,
  },
  {
    id: "acct_chase_sapphire",
    userId: MOCK_USER_ID,
    name: "Chase Sapphire",
    type: "liability.credit_card",
    institution: "Chase",
    accountNumberMasked: ".... 3398",
    currency: "INR",
    balance: -3210.45,
  },
];

export const SEED_TRANSACTIONS: MoneyTransaction[] = [
  {
    id: "txn_whole_foods",
    userId: MOCK_USER_ID,
    accountId: "acct_chase_checking",
    date: "2026-07-28",
    direction: "debit",
    type: "expense",
    amount: 89.43,
    description: "Whole Foods Market",
    merchant: "Whole Foods Market",
    category: "Groceries",
    narration: "POS PURCHASE WHOLEFDS #102",
  },
  {
    id: "txn_stripe_salary",
    userId: MOCK_USER_ID,
    accountId: "acct_chase_checking",
    date: "2026-07-25",
    direction: "credit",
    type: "salary",
    amount: 8500,
    description: "Stripe Inc. — Salary",
    merchant: "Stripe Inc.",
    narration: "ACH CREDIT STRIPE PAYROLL",
  },
  {
    id: "txn_netflix",
    userId: MOCK_USER_ID,
    accountId: "acct_chase_sapphire",
    date: "2026-07-22",
    direction: "debit",
    type: "expense",
    amount: 15.99,
    description: "Netflix",
    merchant: "Netflix",
    category: "Subscriptions",
    narration: "NETFLIX.COM",
  },
  {
    id: "txn_uber",
    userId: MOCK_USER_ID,
    accountId: "acct_chase_sapphire",
    date: "2026-07-20",
    direction: "debit",
    type: "expense",
    amount: 24.5,
    description: "Uber",
    merchant: "Uber",
    category: "Transport",
    narration: "UBER TRIP HELP.UBER.COM",
  },
  {
    id: "txn_transfer_savings",
    userId: MOCK_USER_ID,
    accountId: "acct_chase_checking",
    date: "2026-07-15",
    direction: "debit",
    type: "internal_transfer",
    amount: 1000,
    description: "Transfer to Marcus Savings",
    merchant: "Marcus",
    narration: "ONLINE TRANSFER TO SAVINGS",
    transferRole: "out",
  },
  {
    id: "txn_pharmacy",
    userId: MOCK_USER_ID,
    accountId: "acct_chase_checking",
    date: "2026-07-12",
    direction: "debit",
    type: "expense",
    amount: 42.18,
    description: "CVS Pharmacy",
    merchant: "CVS Pharmacy",
    category: "Healthcare",
    narration: "CVS/PHARMACY #4481",
  },
  {
    id: "txn_amazon",
    userId: MOCK_USER_ID,
    accountId: "acct_chase_sapphire",
    date: "2026-07-08",
    direction: "debit",
    type: "expense",
    amount: 67.2,
    description: "Amazon",
    merchant: "Amazon",
    category: "Shopping",
    narration: "AMAZON.COM*AB12CD",
  },
  {
    id: "txn_rent",
    userId: MOCK_USER_ID,
    accountId: "acct_chase_checking",
    date: "2026-07-01",
    direction: "debit",
    type: "expense",
    amount: 2400,
    description: "Rent — July",
    merchant: "Landlord LLC",
    category: "Housing",
    narration: "RENT PAYMENT JULY",
  },
];

/** Seeded monthly nets for chart fidelity (Sep → Jul). */
export const SEED_CASH_FLOW: CashFlowPoint[] = [
  { month: "Sep", net: 2100 },
  { month: "Oct", net: 2800 },
  { month: "Nov", net: 1900 },
  { month: "Dec", net: 3200 },
  { month: "Jan", net: 2500 },
  { month: "Feb", net: 3100 },
  { month: "Mar", net: 2700 },
  { month: "Apr", net: 3600 },
  { month: "May", net: 3290 },
  { month: "Jun", net: 4860 },
  { month: "Jul", net: 3420 },
];
